export const INIT_GET_ITEMS = 'INIT_GET_ITEMS';

export const SET_STREAMS = 'SET_STREAMS';
export const SET_SUBJECTS = 'SET_SUBJECTS';
export const SET_QPAPERS = 'SET_QPAPERS';
export const SET_SYLLABUS = 'SET_SYLLABUS';
export const SELECT_ITEM = 'SELECT_ITEM';

export const SET_SELECTED_ITEM = 'SET_SELECTED_ITEM';

export const UI_SELECTING_ITEM = 'UI_SELECTING_ITEM';
export const UI_TOGGLE_PATTERN = 'UI_TOGGLE_PATTERN';
export const UI_CLOSE_SELECT_ITEMS = 'UI_CLOSE_SELECT_ITEMS';

export const ADMIN_SET_STREAMS = 'ADMIN_SET_STREAMS';
export const ADMIN_SET_SUBJECTS = 'ADMIN_SET_SUBJECTS';
export const ADMIN_SET_QPAPERS = 'ADMIN_SET_QPAPERS';
export const ADMIN_SET_SYLLABUS = 'ADMIN_SET_SYLLABUS';

export const ADMIN_OPEN_MODAL = 'ADMIN_OPEN_MODAL';
export const ADMIN_CLOSE_MODAL = 'ADMIN_CLOSE_MODAL';
export const ADMIN_EDIT_INIT = 'ADMIN_EDIT_INIT';
export const ADMIN_CHANGE_INPUTFIELD = 'ADMIN_CHANGE_INPUTFIELD';
export const ADMIN_CHANGE_UPLOAD = '';
export const ADMIN_CHANGE_DATA_CREATOR_STATUS = 'ADMIN_CHANGE_DATA_CREATOR_STATUS';
export const ADMIN_SET_QPAPER_DATA = 'ADMIN_SET_QPAPER_DATA';
export const ADMIN_CLEAR_QPAPER_DATA = 'ADMIN_CLEAR_QPAPER_DATA';

export const ADMIN_SELECT_STREAM = 'ADMIN_SELECT_ITEM';
export const ADMIN_SELECT_SUBJECT = 'ADMIN_SELECT_SUBJECT';
export const ADMIN_SELECT_QPAPER = 'ADMIN_SELECT_QPAPER';
export const ADMIN_SELECT_SYLLABUS = 'ADMIN_SELECT_SYLLABUS';


export const AUTH_INIT = 'AUTH_INIT';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CLOSE = 'AUTH_CLOSE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';